### ISSUE TITLE
hello bike任何页面都不支持？

### ISSUE THREAD

**Issue by ghoshorn** [zhaobozhen/Anywhere-Docs#1]
每次打开哈罗单车，都要再弹出个框，关掉了再点一下才能扫码骑车，这个时候感觉anywhere-会 超级方便，但是貌似每个页面我都试了一下，都打不开呢？

**Comment by ghoshorn** [comment]
不是 很了解安卓，不过应该有页面是activity，有的是fragment？怎么区分呢

**Comment by zhaobozhen** [comment]
> 不是 很了解安卓，不过应该有页面是activity，有的是fragment？怎么区分呢

是的，即使是 Root 模式现在也还有很多限制。比如不能打开 fragment、很多 Activity 需要 Intent extras 才能正确启动（现在支持添加基础的 extras）。对于这些无法正常打开的页面我以后想用无障碍模拟点击实现，虽然这种实现的体验并不太好，但也暂时想不出什么别的办法了……
