### ISSUE TITLE
Is there any plan to add tiles to power menu for Android 11?

### ISSUE THREAD

**Issue by sky96111** [zhaobozhen/Anywhere-Docs#13]
Like "Tasker" and "Power menu controls". This may be a elegent way to run anywhere tiles for Android 11.

Is there any plan to support this feature?
 https://developer.android.com/guide/topics/ui/device-control

**Comment by zhaobozhen** [comment]
Yes, I have tried supporting the Power Menu Control a few months ago but failed since Google's APIs make me confused. Maybe I will try again in the future.

**Comment by sky96111** [comment]
Supported now
